seed: 42

dataset:
    psnr_border : 40
    ber_border : 0.25
    target_dir : './data/dataset_new'
    train_dir : './imagenette2/train'
    val_dir : './imagenette2/val'
    wm_len_bytes : 4
    methods : ['dwtDctSvd', 'dwtDct']