dataset_path : 'data/dataset'
model_name : 'ResNet'
head_only : false
lr_base : 1.e-4
lr_step : 0.999
n_epochs: 16
train_proportion: 0.8
shuffle: true
batch_size: 32

optimizer:
  name: 'SGD'
  params:
    momentum: 0.9
